# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Stefan personal blog
tagline:          
url:              http://stha.github.io
paginate:         1
baseurl:          /
author:
  name:           Stefan Hasenstab
  url:            https://twitter.com/b00nb0b
  email:          b00nb0b@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/stha/stha.github.io
  
pages_list:       
  About: 'about'
  Archive: 'archive'
  Feed: 'atom.xml'
