# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Stefan
tagline:          
url:              http://b00nb0b.github.io/blog/
paginate:         1
baseurl:          http://b00nb0b.github.io/blog/
author:
  name:           Stefan Hasenstab
  url:            https://twitter.com/b00nb0b
  email:          b00nb0b@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/b00nb0b/blog
  
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
